version: '3.1'
services:
  master:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=LAB
      - MYSQL_ROOT_PASSWORD=
  slave:
    image: mysql:latest
    ports:
      - "3306"
    depends_on:
      - master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=
      - MYSQL_MASTER_HOST=master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_USER=user
      - MYSQL_PASSWORD=
      - MYSQL_MASTER_ROOT_PASSWORD=